### PR TITLE
Updated README file

### PR DESCRIPTION
**Pull request by cmcaboy**
I made the following changes to the README file:

1) Added a props table
2) Added a Typescript section
3) Added a link to McAboy Digital's youtube tutorial.

I hope this helps!
Thanks!

### CODE REVIEW

**Comment by naqvitalha** [comment]
Apologies for the delay. The build is failing and did you update your video mentioning that non deterministic rendering is supported?

**Comment by cmcaboy** [comment]
Hey, I'm not sure why the build is failing. I only updated the readme. I
have not updated the video. Would a note in the description suffice?

**Comment by cmcaboy** [comment]
Ok. Ill have to do some investigation when I get home. My schedule is a bit
tight this week so it may take a few days to turn around.

**Comment by naqvitalha** [comment]
Sure, take your time.

**Comment by naqvitalha** [comment]
@cmcaboy You can also break this PR. Include video link once it is ready.

**Comment by cmcaboy** [comment]
I went ahead and removed the link for now. When I update the video, I'll create a new pull request.

Thanks!

**Pull request merged**
