### PR TITLE
fix(rtl): fixed render element when languages is right to left

### PR DESCRIPTION
**Pull request by Matergi**
Only for Android when the device is in RTL language and is in horizontal mode the items not rendering

### CODE REVIEW

**Comment by Matergi** [comment]
resolve: #502 #322

**Comment by fai9al7dad** [comment]
thanks tried it on dist.. this did fix the bug

please merge it if everything is good

**Comment by demedos** [comment]
+1. @naqvitalha can this be merged?

**Review by demedos — APPROVED** [review]

**Review by bestori — DISMISSED** [review]
Works great for me, recommend merge

**Comment by bestori** [comment]
@Matergi don't forger to rebase with main..! :)

**Comment by Budaa** [comment]
@Matergi Are there any prerequisites for it to work? Do I need to set any other props on the list, apart from horizontal? 
I'm trying it on the FlashList and it doesn't help unfortunately. It only renders the first and last element of the list and has blank space in between.

**Comment by bestori** [comment]
> @Matergi Are there any prerequisites for it to work? Do I need to set any other props on the list, apart from horizontal? I'm trying it on the FlashList and it doesn't help unfortunately. It only renders the first and last element of the list and has blank space in between.

@Budaa can you share non-working code sample?

@Matergi once we have this sorted out I will continue. Thank you!

**Comment by 1nspir3d** [comment]
> @Matergi Are there any prerequisites for it to work? Do I need to set any other props on the list, apart from horizontal? I'm trying it on the FlashList and it doesn't help unfortunately. It only renders the first and last element of the list and has blank space in between.

how about min reproduce repo/snack?

**Comment by 1nspir3d** [comment]
@Budaa @bestori I can confirm that this fix is indeed fixes a problem with horizontal RTL list. Just tried it out on my project and everything seems to work fine.

However, I had to apply this fix directly into `recyclerlistview/dist/reactnative/core/VirtualRenderer.js`. Applying this to `recyclerlistview/src/core/VirtualRenderer.ts` has no effect whatsoever.

Are there any additional steps required when you apply this fix to `recyclerlistview/src/core/VirtualRenderer.ts`?

**Review by numandev1 — APPROVED** [review]

**Comment by vanhai989** [comment]
I'm still facing this problem. is there anyone can help me how to fix this one in react native 0.70.13 and "recyclerlistview": "^4.2.0",. Thank you

**Comment by Matergi** [comment]
change library...

**Pull request closed without merging**
