### PR TITLE
added masonary layout

### PR DESCRIPTION
**Pull request by hovox**

### CODE REVIEW

**Comment by hovox** [comment]
Here is another branch where I have added LayoutManager as interface, should I merge it to this branch ?

**Comment by naqvitalha** [comment]
@hovox This is super cool. Let's complete externalising LayoutManager first then we'll come to this. Open it as a separate PR.
Also, if you want you can own the MasonryLayoutManager in your own repository. People needing it can import it as an external dependency.

**Comment by hovox** [comment]
I'm trying to test it. It's a little harder for me because I'm a native iOS/Android developer. Never worked with typescript.

**Comment by naqvitalha** [comment]
Great! Let me know if you need my help

**Comment by hovox** [comment]
Could you please check #84 issue? Without it fixed, we can't use the framework.

**Comment by naqvitalha** [comment]
I will be externalising layout manager soon. Your layout manager can then be independently integrated.

**Comment by MelindaFancsal** [comment]
Hi, will there be an update on this? I can't wait to see this merged.

**Comment by ign699** [comment]
Yeah would be awesome to see this merged !

**Comment by tafelito** [comment]
@naqvitalha are you still working on externalizing the layout manager? Is there anything I can do to help?

**Comment by naqvitalha** [comment]
@tafelito Layout manager is already externalised. Check a sample layout provider: https://github.com/muskeinsingh/recyclerlistview-gridlayoutprovider. You can write a masonry one, that'll be great!

**Comment by NrqhEIcsRi004** [comment]
This feature is great, can you merge it? @naqvitalha @hovox

**Comment by pribeh** [comment]
Any update on this?

**Comment by Jose4gg** [comment]
Any updates with this?

**Comment by nesscx** [comment]
Any updates on this?

**Comment by ashokkumar88** [comment]
@tafelito any chance to work with masonry layout?

**Comment by lukebars** [comment]
Did you manage to complete it @hovox ?

**Comment by alexandrius** [comment]
@naqvitalha @hovox  Any updates regarding MasonryLayoutProvider?

**Pull request closed without merging**
