### PR TITLE
Adding support for stableIds

### PR DESCRIPTION
**Pull request by naqvitalha**

### CODE REVIEW

**Comment by AbdallaMohamed** [comment]
Thanks for continously improving RLV, @naqvitalha
I'm curious about what this stableIds feature means and what it could be used for. Also, it would be really nice if we, users of RLV,  could get an example of the newly introduced animation hooks feature and how to do like a simple fade in animation or something like that. Thanks for all your efforts!

**Comment by AbdallaMohamed** [comment]
So excited this is finally merged! Any tips on how to implement sticky headers?

**Comment by naqvitalha** [comment]
What confusion do you have? I believe you already have done that before

**Comment by AbdallaMohamed** [comment]
@naqvitalha I was talking about a sticky rows feature in RLV itself. I'll implement it with that external scrollview though. Thanks for your efforts, @naqvitalha. I can't find a git tag or release for the new features though. Am I missing something?

**Comment by AbdallaMohamed** [comment]
One of the things I've noticed with my solution is that if a header row can sometimes not show up if it's not rendered. How do you make sure a specific row is always rendered. That's quite the challenge..

**Pull request merged**
