### PR TITLE
Add inverted prop

### PR DESCRIPTION
**Pull request by tafelito**
@naqvitalha This is the same PR I created before with the inverted prop with the rewrite using TS. You mentioned in the old PR that we might be able to do this without changing the view renderer but I need to change both the view within the ScrollView and the ViewRenderer. Did you mean something else?

Also you wanted to keep the isHorizontal to a minimum, is something like this what you were thinking?

This is just a first draft as this only works for web now and only works if `useWindowScroll=false`

### CODE REVIEW

**Comment by naqvitalha** [comment]
So, my suggestion would be to write an `externalScrollView` that extends from the existing one. Internally it will just place one more `div` which is rotated again. Like a `div` inside a `div`. So, to invert we can just pass `InvertedScrollView` instead of setting a prop. We added `externalScrollView` feature to enable things like these without touching the core logic. Try it out, it'll be much cleaner to do and can also be done easily for RN. Write one for web, I'll add RN logic.

**Comment by tafelito** [comment]
@naqvitalha If I try to set the externalScrollView in `RecyclerListView` I get this TS error

image

Any ideas why?

**Comment by naqvitalha** [comment]
Forcefully cast to BaseScrollView for now by casting to any first. You can fix the type in RLV. The type mentioned in RLV props is incorrect. Bug on my end. But it works fine.

**Comment by tafelito** [comment]
@naqvitalha even using an InvertedScrollView, the ViewRender still needs the transform because not only the list has to be inverted, also every item on the list

**Comment by naqvitalha** [comment]
Think of it this way:
```js
render(){
       return <ScrollView style={{scaleY:-1}}>
                        <div style={{scaleY:-1}}>
                            {this.props.children}
                        </div>
                  </ScrollView>
}
```
Wouldn't this achieve the same thing?

**Comment by tafelito** [comment]
@naqvitalha no I don't think that would work. And the biggest issue is that this doesn't work when using windows scroll. Do we need that to work? I don't see it as necessary but maybe there is a use case for it. In native, if you want to scroll the whole screen not just the list, you add the components as header or footer, that way you can scroll everything on screen, not just the list

**Comment by naqvitalha** [comment]
@tafelito I'll pull this in another branch. I'll add the RN implementation and then take it forward. Thanks a lot for your help :)

**Comment by jfr3000** [comment]
Is there any update on this? Having `inverted` would be great. Installing from the inverted-branch doesn't work sadly.

**Comment by gut4** [comment]
Any update on this?

**Comment by holgersindbaek** [comment]
Same question as @gut4... will this be released?

**Comment by eseQ** [comment]
Aaaaand 2 more years =)

**Pull request merged**
